"""Initial migration

Revision ID: 00e89dd95193
Revises: 3d6cf83f66ce
Create Date: 2024-10-09 21:09:36.398233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00e89dd95193'
down_revision: Union[str, None] = '3d6cf83f66ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'specifications')
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'image_links')
    op.drop_column('products', 'created_at')
    op.drop_column('products', 'price')
    op.drop_column('products', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('price', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('image_links', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('specifications', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
